// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.aleprueba.ale.client.managed.request;

import com.aleprueba.ale.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory {

    ModelRequest modelRequest();

    CuentasRequest cuentasRequest();
}
