// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.aleprueba.ale.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("com.mlopez.appname.entities.Cuentas")
@ServiceName("com.mlopez.appname.entities.Cuentas")
public interface CuentasRequest extends RequestContext {

    abstract InstanceRequest<com.aleprueba.ale.client.managed.request.CuentasProxy, java.lang.Void> persist();

    abstract InstanceRequest<com.aleprueba.ale.client.managed.request.CuentasProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countCuentases();

    abstract Request<com.aleprueba.ale.client.managed.request.CuentasProxy> findCuentas(Long id);

    abstract Request<java.util.List<com.aleprueba.ale.client.managed.request.CuentasProxy>> findAllCuentases();

    abstract Request<java.util.List<com.aleprueba.ale.client.managed.request.CuentasProxy>> findCuentasEntries(int firstResult, int maxResults);
}
