// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.aleprueba.ale.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("com.aleprueba.ale.Model")
@ServiceName("com.aleprueba.ale.Model")
public interface ModelRequest extends RequestContext {

    abstract InstanceRequest<com.aleprueba.ale.client.managed.request.ModelProxy, java.lang.Void> persist();

    abstract InstanceRequest<com.aleprueba.ale.client.managed.request.ModelProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countModels();

    abstract Request<com.aleprueba.ale.client.managed.request.ModelProxy> findModel(Long id);

    abstract Request<java.util.List<com.aleprueba.ale.client.managed.request.ModelProxy>> findAllModels();

    abstract Request<java.util.List<com.aleprueba.ale.client.managed.request.ModelProxy>> findModelEntries(int firstResult, int maxResults);
}
