// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.aleprueba.ale.client.managed.ui;

import com.aleprueba.ale.client.managed.request.ApplicationEntityTypesProcessor;
import com.aleprueba.ale.client.managed.request.CuentasProxy;
import com.aleprueba.ale.client.managed.request.ModelProxy;
import com.aleprueba.ale.client.scaffold.place.ProxyListPlace;
import com.google.gwt.text.shared.AbstractRenderer;

public abstract class ApplicationListPlaceRenderer_Roo_Gwt extends AbstractRenderer<ProxyListPlace> {

    public String render(ProxyListPlace object) {
        return new ApplicationEntityTypesProcessor<String>() {

            @Override
            public void handleModel(ModelProxy isNull) {
                setResult("Models");
            }

            @Override
            public void handleCuentas(CuentasProxy isNull) {
                setResult("Cuentass");
            }
        }.process(object.getProxyClass());
    }
}
