// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.aleprueba.ale;

import java.lang.String;

privileged aspect Model_Roo_JavaBean {
    
    public String Model.getMessage() {
        return this.message;
    }
    
    public void Model.setMessage(String message) {
        this.message = message;
    }
    
}
