// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.aleprueba.ale.client.managed.activity;

import com.aleprueba.ale.client.managed.request.ApplicationEntityTypesProcessor;
import com.aleprueba.ale.client.managed.request.ApplicationRequestFactory;
import com.aleprueba.ale.client.managed.request.CuentasProxy;
import com.aleprueba.ale.client.managed.request.ModelProxy;
import com.aleprueba.ale.client.managed.ui.CuentasListView;
import com.aleprueba.ale.client.managed.ui.CuentasMobileListView;
import com.aleprueba.ale.client.managed.ui.ModelListView;
import com.aleprueba.ale.client.managed.ui.ModelMobileListView;
import com.aleprueba.ale.client.scaffold.ScaffoldApp;
import com.aleprueba.ale.client.scaffold.place.ProxyListPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;

public abstract class ApplicationMasterActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyListPlace)) {
            return null;
        }
        ProxyListPlace listPlace = (ProxyListPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleModel(ModelProxy isNull) {
                setResult(new ModelListActivity(requests, ScaffoldApp.isMobile() ? ModelMobileListView.instance() : ModelListView.instance(), placeController));
            }

            @Override
            public void handleCuentas(CuentasProxy isNull) {
                setResult(new CuentasListActivity(requests, ScaffoldApp.isMobile() ? CuentasMobileListView.instance() : CuentasListView.instance(), placeController));
            }
        }.process(listPlace.getProxyClass());
    }
}
